### ISSUE TITLE
"unknown build" for build re-runs

### ISSUE THREAD

**Issue by mattdodge** [mockersf/concourse-slack-notifier#61]
In Concourse 6.0 you can now "re-run" a build. If you re-run build 314, for example, it will create a new build 314.1 consisting of the re-run. This Slack notification resource doesn't seem to like that and displays "unknown build" for these re-runs.

Screenshot:
![image](https://user-images.githubusercontent.com/797259/83476107-a7e8ba80-a444-11ea-8b05-fe244c66e767.png)

To reproduce:
1. Use Concourse >= 6.0
1. Run a job that triggers a slack notification.
2. Re-run that job using the rerun button or [the fly CLI](https://concourse-ci.org/jobs.html#fly-rerun-build)

**Comment by mockersf** [comment]
Thank you for reporting this!

It should work if you depend on latest image docker, I'll wait either for us to update our instance at work or for you to confirm it work before pushing a new tag.

**Comment by mattdodge** [comment]
Yep that's working now for me! Ran a check-resource-type against the latest tag and the build number comes through correctly now. Thanks for the quick turnaround!

**Comment by mockersf** [comment]
released v0.2.0 with another fix for concourse 6!
