### ISSUE TITLE
Error: relative URL without a base

### ISSUE THREAD

**Issue by mvdkleijn** [mockersf/concourse-slack-notifier#77]
I'm getting the above error (relative URL without a base) when trying to set the url to something like `(( slack-url ))` which is stored in our credential backend.

**Comment by mockersf** [comment]
hello !
Concourse is responsible from getting the actual value from the credential backend, and then the url is parsed with [`Url::parse`](https://docs.rs/reqwest/0.10.8/reqwest/struct.Url.html#method.parse).

You are getting this error: https://docs.rs/url/2.1.1/url/enum.ParseError.html

this error can be:
- concourse can't retrieve the value from the credential backend
- the value is not a valid url

for example here is how the url is validated, if you want to try with your url: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=9fdae3221cb310bd88db5ad24070dee2
